# Generated by Django 5.0.4 on 2025-03-08 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_userprofile_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='course_documents/'),
        ),
        migrations.AddField(
            model_name='course',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
