# Generated by Django 5.0.4 on 2025-03-10 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_review_is_approved'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='completedlesson',
            options={'verbose_name': 'Завършен урок', 'verbose_name_plural': 'Завършени уроци'},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'Курс', 'verbose_name_plural': 'Курсове'},
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'verbose_name': 'Урок', 'verbose_name_plural': 'Уроци'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Поръчка', 'verbose_name_plural': 'Поръчки'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'Въпрос', 'verbose_name_plural': 'Въпроси'},
        ),
        migrations.AlterModelOptions(
            name='quiz',
            options={'verbose_name': 'Тест', 'verbose_name_plural': 'Тестове'},
        ),
        migrations.AlterModelOptions(
            name='quizresult',
            options={'verbose_name': 'Резултат от тест', 'verbose_name_plural': 'Резултати от тестове'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': 'Ревю', 'verbose_name_plural': 'Ревюта'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'Потребител', 'verbose_name_plural': 'Потребители'},
        ),
    ]
