# Generated by Django 5.0.4 on 2025-03-10 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_alter_completedlesson_options_alter_course_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SliderImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заглавие')),
                ('image', models.ImageField(upload_to='slider_images/', verbose_name='Снимка за слайдера')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Слайдер изображение',
                'verbose_name_plural': 'Слайдер изображения',
            },
        ),
    ]
