# Generated by Django 5.0.4 on 2025-03-10 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_sliderimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='sliderimage',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.course', verbose_name='Курс'),
        ),
        migrations.AddField(
            model_name='sliderimage',
            name='text',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Текст върху слайдера'),
        ),
    ]
